### ISSUE TITLE
plugin seems not loaded for any content type

### ISSUE THREAD

**Issue by simongcc** [whomwah/qlstephen#84] opened 2019-10-06 03:32 UTC
My system is MacOS Sierra 10.12.6 running in English as default language
I have installed QLStephen, since it did not work as expected, I try to see the loaded plugin by
qlmanage -m plugins

I have reset cache and list with
qlmanage -r cache
qlmanage -r 
to make sure it is reloaded, I have tried other new plugins too which work without problem.

The plugin is installed thru
`brew cask install qlstephen` (version is 1.44)
file is located at `/Users/USERNAME/Library/QuickLook/QLStephen.qlgenerator`  with other plugins

If I test manually with such as CSS file
`qlmanage -g /Users/USERNAME/Library/QuickLook/QLStephen.qlgenerator -c public.css -p style.css`
It work.

Is there any conflict?
Is there any debug info I can provide more information for checking?
Can I manually register content type for QLStephen?

Many thanks.

The qlmanage loaded plugin list as follow
```
  public.item -> /Library/QuickLook/PatternQuickLook.qlgenerator (1 - loaded)
  public.img -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  org.openxmlformats.presentationml.slideshow -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.adobe.pdf -> /System/Library/QuickLook/PDF.qlgenerator (720.7)
  com.apple.localized-pdf-bundle -> /System/Library/QuickLook/LocPDF.qlgenerator (720.7)
  public.3d-content -> /System/Library/QuickLook/SceneKit.qlgenerator (386.13)
  com.apple.iwork.keynote.key -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.ical.bookmark -> /System/Library/QuickLook/iCal.qlgenerator (720.7)
  com.apple.application -> /System/Library/QuickLook/StandardBundles.qlgenerator (720.7)
  public.zip -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  com.microsoft.powerpoint.pot -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.word.doc -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.openxmlformats.wordprocessingml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.keynote.sffkey -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.ichat.ichat -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.notes.externalrecord -> /System/Library/QuickLook/Notes.qlgenerator (719.81)
  public.dcm -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  com.microsoft.word.dot -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.keynote.sffkth -> /Library/QuickLook/iWork.qlgenerator (166)
  public.data -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  org.openxmlformats.presentationml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.keynote.key -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.mail.email -> /System/Library/QuickLook/Mail.qlgenerator (3273)
  com.apple.bundle -> /Library/QuickLook/PatternQuickLook.qlgenerator (1 - loaded)
  com.apple.iwork.pages.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (166)
  public.movie -> /System/Library/QuickLook/Movie.qlgenerator (720.7)
  com.apple.iwork.keynote.kth -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.iwork.numbers.sffnumbers -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.package -> /System/Library/QuickLook/Package.qlgenerator (720.7)
  org.openxmlformats.wordprocessingml.document.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  dyn.ah62d4rv4ge80w5xxsa -> /Library/QuickLook/QLInsta360Picture.qlgenerator (1)
  com.apple.iwork.pages.sffpages -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.ical.ics -> /System/Library/QuickLook/iCal.qlgenerator (720.7)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  org.openxmlformats.wordprocessingml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ical.ics.event -> /System/Library/QuickLook/iCal.qlgenerator (720.7)
  com.microsoft.excel.xlt -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.numbers.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.iwork.keynote.key-tef -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.ibooksauthor.book -> /Library/QuickLook/iBooksAuthor.qlgenerator (1.0)
  com.apple.internet-location -> /System/Library/QuickLook/Clippings.qlgenerator (720.7)
  com.rsa.pkcs-12 -> /System/Library/QuickLook/Security.qlgenerator (55079.50.4)
  org.openxmlformats.presentationml.slideshow.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.word.stationery -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ibooks-folder -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  public.x509-printable-encoded-archive -> /System/Library/QuickLook/Security.qlgenerator (55079.50.4)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  org.openxmlformats.wordprocessingml.document -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.quicklook-generator -> /Library/QuickLook/PatternQuickLook.qlgenerator (1 - loaded)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  com.apple.systempreference.prefpane -> /System/Library/QuickLook/StandardBundles.qlgenerator (720.7)
  org.nema.dicom -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  org.openxmlformats.spreadsheetml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.keychain -> /System/Library/QuickLook/Security.qlgenerator (55079.50.4)
  public.font -> /System/Library/QuickLook/Font.qlgenerator (720.7)
  public.x509-certificate -> /System/Library/QuickLook/Security.qlgenerator (55079.50.4)
  com.apple.iwork.pages.template -> /Library/QuickLook/iWork.qlgenerator (166)
  com.adobe.illustrator.ai-image -> /System/Library/QuickLook/EPS.qlgenerator (720.7)
  public.vcard -> /System/Library/QuickLook/Contact.qlgenerator (720.7)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (720.7)
  org.openxmlformats.presentationml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  dyn.ah62d4rv4ge80w5xxs2 -> /Library/QuickLook/QLInsta360Picture.qlgenerator (1)
  org.openxmlformats.spreadsheetml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.numbers.numbers -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.plugin -> /Library/QuickLook/PatternQuickLook.qlgenerator (1 - loaded)
  com.apple.iwork.pages.pages -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.ichat.transcript -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.mail.emlx -> /System/Library/QuickLook/Mail.qlgenerator (3273)
  com.apple.iconset -> /System/Library/QuickLook/Icon.qlgenerator (720.7)
  com.apple.addressbook.group -> /System/Library/QuickLook/Contact.qlgenerator (720.7)
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  public.lsm -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  org.idpf.epub-container -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  com.apple.addressbook.person -> /System/Library/QuickLook/Contact.qlgenerator (720.7)
  com.apple.safari.history -> /System/Library/QuickLook/Bookmark.qlgenerator (720.7)
  public.html -> /System/Library/QuickLook/Web.qlgenerator (720.7)
  com.apple.iwork.numbers.template -> /Library/QuickLook/iWork.qlgenerator (166)
  com.microsoft.powerpoint.pps -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  com.apple.safari.bookmark -> /System/Library/QuickLook/Bookmark.qlgenerator (720.7)
  public.audio -> /System/Library/QuickLook/Audio.qlgenerator (720.7)
  org.idpf.epub-folder -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  com.apple.pict -> /System/Library/QuickLook/Clippings.qlgenerator (720.7)
  public.xhtml -> /System/Library/QuickLook/Web.qlgenerator (720.7)
  org.openxmlformats.presentationml.presentation.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.finder.pictclipping -> /System/Library/QuickLook/Clippings.qlgenerator (720.7)
  com.apple.ical.bookmark.todo -> /System/Library/QuickLook/iCal.qlgenerator (720.7)
  com.apple.iwork.numbers.numbers-tef -> /Library/QuickLook/iWork.qlgenerator (166)
  com.apple.webarchive -> /System/Library/QuickLook/Web.qlgenerator (720.7)
  org.openxmlformats.presentationml.presentation -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (720.7)
  com.apple.private.live-photo-bundle -> /System/Library/QuickLook/LivePhoto.qlgenerator (720.7)
  public.text -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  public.image -> /System/Library/QuickLook/Image.qlgenerator (720.7)
  org.openxmlformats.spreadsheetml.sheet -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.microsoft.excel.xls -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.directory -> /Library/QuickLook/PatternQuickLook.qlgenerator (1 - loaded)
  public.css -> /Applications/OsiriX Lite.app/Contents/Library/QuickLook/OsiriXQuickLookPlugin.qlgenerator (6.0 - loaded)
  org.openxmlformats.spreadsheetml.sheet.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (720.7)
  com.apple.iwork.pages.pages-tef -> /Library/QuickLook/iWork.qlgenerator (166)
  com.microsoft.powerpoint.ppt -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.comma-separated-values-text -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ical.ics.todo -> /System/Library/QuickLook/iCal.qlgenerator (720.7)
  com.adobe.encapsulated-postscript -> /System/Library/QuickLook/EPS.qlgenerator (720.7)
  com.evernote.note-metadata2 -> /Applications/Evernote.app/Contents/Library/QuickLook/ENQuickLookGenerator.qlgenerator (1.0)
```

**Comment by simongcc** [comment] 2019-10-06 05:11
After uninstalling osiriX to prevent its quicklook to load and then reset.
QLStephen load showing public.data as supported content type

**Comment by xiruizhao** [comment] 2019-12-26 13:48
The problem is solved, right? Please close this issue.

**Comment by simongcc** [comment] 2019-12-26 14:11
I think it resolved. Thanks for reminding.

**Closed** 2019-12-26 14:11 UTC
